#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#nitrogen --restore &            # set wallpaper
#tint2 &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources & # uncomment to use Xresources colors/settings on startup
mpd &                           # music player daemon-you might prefer it as a service though
#picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
#dunst &                         # dunst for notifications
xset r rate 300 50 &            # Speed xrate up
unclutter &                     # Remove mouse when idle
